#index:
#    path: /
#    controller: App\Controller\DefaultController::index

health_check:
  path: /
  controller: App\Controller\HealthCheck
  methods: [ GET ]

register:
  path: /api/register
  controller: App\Controller\User\Register
  methods: [ POST ]
